parameters:
#    aston_user.example.class: Aston\UserBundle\Example

services:
#    aston_user.example:
#        class: %aston_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
