parameters:
#    aston_livre.example.class: Aston\LivreBundle\Example

services:
#    aston_livre.example:
#        class: %aston_livre.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
